// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIyMAEXw5N0XvRJZ4nR1Z0DITREtWe1iY',
    appId: '1:568197070642:web:5e6a4bc8b3da40add0a12b',
    messagingSenderId: '568197070642',
    projectId: 'ticketingapp-e54e7',
    authDomain: 'ticketingapp-e54e7.firebaseapp.com',
    storageBucket: 'ticketingapp-e54e7.firebasestorage.app',
    measurementId: 'G-CWE38D060Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmdXW8SxTbxGqDQQneAAw1xKeJ1xybEJ8',
    appId: '1:568197070642:android:bd4cf1a989b3790bd0a12b',
    messagingSenderId: '568197070642',
    projectId: 'ticketingapp-e54e7',
    storageBucket: 'ticketingapp-e54e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp05ZcY349wc_goi8tL1BUty_B6VymSFE',
    appId: '1:568197070642:ios:7cc893d49f91a2ddd0a12b',
    messagingSenderId: '568197070642',
    projectId: 'ticketingapp-e54e7',
    storageBucket: 'ticketingapp-e54e7.firebasestorage.app',
    iosBundleId: 'com.example.ticketingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp05ZcY349wc_goi8tL1BUty_B6VymSFE',
    appId: '1:568197070642:ios:7cc893d49f91a2ddd0a12b',
    messagingSenderId: '568197070642',
    projectId: 'ticketingapp-e54e7',
    storageBucket: 'ticketingapp-e54e7.firebasestorage.app',
    iosBundleId: 'com.example.ticketingapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIyMAEXw5N0XvRJZ4nR1Z0DITREtWe1iY',
    appId: '1:568197070642:web:511e80721c6e1790d0a12b',
    messagingSenderId: '568197070642',
    projectId: 'ticketingapp-e54e7',
    authDomain: 'ticketingapp-e54e7.firebaseapp.com',
    storageBucket: 'ticketingapp-e54e7.firebasestorage.app',
    measurementId: 'G-4ZB5MCBLMV',
  );

}